"""phase3 bills and recurring

Revision ID: ff418f598160
Revises: 9c797c1fb009
Create Date: 2026-10-04 13:32:15.694303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff418f598160'
down_revision: Union[str, None] = '9c797c1fb009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('bills', sa.Column('kind', sa.String(length=20), server_default='custom', nullable=False))
    op.add_column('bills', sa.Column('anchor_day', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('bills', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('reminder_days', sa.JSON(), nullable=True))
    op.add_column('bills', sa.Column('last_paid', sa.Date(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('type', sa.String(length=10), server_default='expense', nullable=False))
    op.add_column('recurring_transactions', sa.Column('merchant_key', sa.String(length=160), server_default='', nullable=False))
    op.add_column('recurring_transactions', sa.Column('last_date', sa.Date(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('anchor_day', sa.Integer(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('recurring_transactions', sa.Column('occurrences', sa.Integer(), server_default='0', nullable=False))
    op.add_column('recurring_transactions', sa.Column('source', sa.String(length=10), server_default='detected', nullable=False))
    # Backfill so any pre-existing rows get a distinct key before the unique index is created.
    op.execute("UPDATE recurring_transactions SET merchant_key = lower(trim(merchant)) WHERE merchant_key = ''")
    op.create_index('uq_recurring_user_type_key', 'recurring_transactions', ['user_id', 'type', 'merchant_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_recurring_user_type_key', table_name='recurring_transactions')
    op.drop_column('recurring_transactions', 'source')
    op.drop_column('recurring_transactions', 'occurrences')
    op.drop_column('recurring_transactions', 'confidence')
    op.drop_column('recurring_transactions', 'anchor_day')
    op.drop_column('recurring_transactions', 'last_date')
    op.drop_column('recurring_transactions', 'merchant_key')
    op.drop_column('recurring_transactions', 'type')
    op.drop_column('bills', 'last_paid')
    op.drop_column('bills', 'reminder_days')
    op.drop_column('bills', 'notes')
    op.drop_column('bills', 'active')
    op.drop_column('bills', 'anchor_day')
    op.drop_column('bills', 'kind')
    # ### end Alembic commands ###
